framework:
    rate_limiter:
        api_public:
            policy: 'fixed_window'
            limit: 300
            interval: '1 hour'
            # identify client by IP
            cache_pool: 'cache.app'
        api_sensitive:
            policy: 'sliding_window'
            limit: 30
            interval: '1 minute'
            cache_pool: 'cache.app'

